"""Pydantic schemas (request/response models)."""
from app.schemas.auth import (
    LoginRequest,
    RefreshRequest,
    TokenPair,
    TokenPayload,
)
from app.schemas.common import (
    Message,
    PaginatedResponse,
    PaginationParams,
)
from app.schemas.intelligence import (
    CompetitorCreate,
    CompetitorRead,
    CompetitorUpdate,
    CustomerSegmentCreate,
    CustomerSegmentRead,
    IndustryCreate,
    IndustryRead,
    MarketCreate,
    MarketRead,
    MarketUpdate,
    OpportunityCreate,
    OpportunityRead,
    RiskCreate,
    RiskRead,
    TrendCreate,
    TrendRead,
)
from app.schemas.reports import (
    ExecutiveBriefRead,
    RecommendationRead,
    ReportRequest,
    ResearchReportRead,
)
from app.schemas.signals import (
    FeedItemRead,
    SignalCreate,
    SignalIngestBatch,
    SignalRead,
)
from app.schemas.system import AlertRead, NotificationRead
from app.schemas.user import CompanyCreate, CompanyRead, UserCreate, UserRead, UserUpdate

__all__ = [
    "LoginRequest",
    "RefreshRequest",
    "TokenPair",
    "TokenPayload",
    "Message",
    "PaginatedResponse",
    "PaginationParams",
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "CompanyCreate",
    "CompanyRead",
    "MarketCreate",
    "MarketRead",
    "MarketUpdate",
    "CompetitorCreate",
    "CompetitorRead",
    "CompetitorUpdate",
    "CustomerSegmentCreate",
    "CustomerSegmentRead",
    "TrendCreate",
    "TrendRead",
    "IndustryCreate",
    "IndustryRead",
    "OpportunityCreate",
    "OpportunityRead",
    "RiskCreate",
    "RiskRead",
    "SignalCreate",
    "SignalRead",
    "SignalIngestBatch",
    "FeedItemRead",
    "ResearchReportRead",
    "ExecutiveBriefRead",
    "RecommendationRead",
    "ReportRequest",
    "AlertRead",
    "NotificationRead",
]
